### ISSUE TITLE
Help! SOS from your fans

### ISSUE THREAD

**Issue by Jackey0903** [mbzuai-oryx/Video-ChatGPT#129]
![Uploading 屏幕截图 2024-12-04 202945.png…]()

Dear author, hello, I ran it locally after deploying the server, but encountered the following error. Due to our limited level, we cannot solve it. Please take a look at where the problem is. Thank you!

**Comment by Jackey0903** [comment]
Here are the detailed information:
2024-12-04 20:11:26 | ERROR | asyncio | Task exception was never retrieved
future: <Task finished name='jy6jl4r0l9j_12' coro=<Queue.process_events() done, defined at /root/miniconda3/lib/python3.12/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 12, 'data': ...on_hash': 'jy6jl4r0l9j'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
           ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 12, 'data': ...on_hash': 'jy6jl4r0l9j'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
