### ISSUE TITLE
During the demo, sometimes an exception occurs

### ISSUE THREAD

**Issue by willzli** [mbzuai-oryx/Video-ChatGPT#18]
2023-06-27 05:01:51 | ERROR | stderr |   File "/home/lizheng/software/miniconda3/envs/video_chatgpt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
2023-06-27 05:01:51 | ERROR | stderr |     result = context.run(func, *args)
2023-06-27 05:01:51 | ERROR | stderr |   File "/home/lizheng/software/miniconda3/envs/video_chatgpt/lib/python3.10/site-packages/gradio/utils.py", line 549, in async_iteration
2023-06-27 05:01:51 | ERROR | stderr |     return next(iterator)
2023-06-27 05:01:51 | ERROR | stderr |   File "/home/lizheng/project/Video-ChatGPT/video_chatgpt/demo/chat.py", line 105, in answer
2023-06-27 05:01:51 | ERROR | stderr |     image_tensor = img_list[0]
2023-06-27 05:01:51 | ERROR | stderr | IndexError: list index out of range

**Comment by hanoonaR** [comment]
Hi @willzli 

Thank you for your interest in our work. This error occurs when the video have not been uploaded. As the note in the demo mentions, Please make sure you press the 'Upload Video' button before submitting a question. This is the case either you upload your own video or choose a video from the samples provided. 

Please let me know if the issue persists. Thank you.

**Comment by ElhamAhmedian** [comment]
2024-06-04 15:56:30 | ERROR | stderr |   warnings.warn(
2024-06-04 15:56:30 | INFO | stdout | Running on local URL:  http://0.0.0.0:7860
2024-06-04 15:56:30 | INFO | stdout |
2024-06-04 15:56:30 | INFO | stdout | To create a public link, set `share=True` in `launch()`.
2024-06-04 15:59:43 | INFO | gradio_web_server | load_demo.. params: {}
2024-06-04 16:00:02 | INFO | gradio_web_server | add_text. ip:. len: 69
2024-06-04 16:00:05 | ERROR | stderr | /opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py:1211: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
2024-06-04 16:00:05 | ERROR | stderr |   warnings.warn(
2024-06-04 16:00:46 | INFO | gradio_web_server | add_text. ip:. len: 9
2024-06-04 16:01:03 | ERROR | stderr | Traceback (most recent call last):
2024-06-04 16:01:03 | ERROR | stderr |   File "/opt/conda/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
2024-06-04 16:01:03 | ERROR | stderr |     output = await app.get_blocks().process_api(
2024-06-04 16:01:03 | ERROR | stderr |   File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
2024-06-04 16:01:03 | ERROR | stderr |     result = await self.call_function(
2024-06-04 16:01:03 | ERROR | stderr |   File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 898, in call_function
2024-06-04 16:01:03 | ERROR | stderr |     prediction = await anyio.to_thread.run_sync(
2024-06-04 16:01:03 | ERROR | stderr |   File "/opt/conda/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-06-04 16:01:03 | ERROR | stderr |     return await get_async_backend().run_sync_in_worker_thread(
2024-06-04 16:01:03 | ERROR | stderr |   File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
2024-06-04 16:01:03 | ERROR | stderr |     return await future
2024-06-04 16:01:03 | ERROR | stderr |   File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
2024-06-04 16:01:03 | ERROR | stderr |     result = context.run(func, *args)
2024-06-04 16:01:03 | ERROR | stderr |   File "/opt/conda/lib/python3.10/site-packages/gradio/utils.py", line 549, in async_iteration
2024-06-04 16:01:03 | ERROR | stderr |     return next(iterator)
2024-06-04 16:01:03 | ERROR | stderr |   File "/RAG/Video-ChatGPT/video_chatgpt/demo/chat.py", line 135, in answer
2024-06-04 16:01:03 | ERROR | stderr |     state.messages[-1][-1] += character
2024-06-04 16:01:03 | ERROR | stderr | TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
