### ISSUE TITLE
ValueError: Some specified arguments are not used by the HfArgumentParser: ['--local-rank=1']

### ISSUE THREAD

**Issue by openworld-lab** [mbzuai-oryx/Video-ChatGPT#26]
Traceback (most recent call last):
  File "/apdcephfs_cq3/share_1311970/Video-ChatGPT/video_chatgpt/train/train_mem.py", line 11, in <module>
    train()
  File "/apdcephfs_cq3/share_1311970/Video-ChatGPT/video_chatgpt/train/train.py", line 482, in train
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/apdcephfs_cq3/share_1311970/lb/miniconda3/envs/video_chatgpt/lib/python3.10/site-packages/transformers/hf_argparser.py", line 341, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: ['--local-rank=0']
Traceback (most recent call last):
  File "/apdcephfs_cq3/share_1311970/Video-ChatGPT/video_chatgpt/train/train_mem.py", line 11, in <module>
    train()
  File "/apdcephfs_cq3/share_1311970/Video-ChatGPT/video_chatgpt/train/train.py", line 482, in train
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/apdcephfs_cq3/share_1311970/lb/miniconda3/envs/video_chatgpt/lib/python3.10/site-packages/transformers/hf_argparser.py", line 341, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: ['--local-rank=2']
Traceback (most recent call last):
  File "/apdcephfs_cq3/share_1311970/Video-ChatGPT/video_chatgpt/train/train_mem.py", line 11, in <module>
    train()
  File "/apdcephfs_cq3/share_1311970/Video-ChatGPT/video_chatgpt/train/train.py", line 482, in train
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/apdcephfs_cq3/share_1311970/lb/miniconda3/envs/video_chatgpt/lib/python3.10/site-packages/transformers/hf_argparser.py", line 341, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: ['--local-rank=1']

**Comment by mmaaz60** [comment]
Hi @openworld-lab,

Thank you for your interest in our work. Please share the PyTorch and Transformers version that you are using? Also are you using `torchrun` or `torch.distributed.launch`? Furthermore, please try installing Transformers using the following command and let me know if it solves the issue,

```
pip install transformers@git+https://github.com/huggingface/transformers.git@cae78c46
```

Thank you and looking forward to hearing from you.

**Comment by openworld-lab** [comment]
Thank you very much, if my GPU device is V100, can I run the code successfully by setting --bf and --tf32 to False?

**Comment by mmaaz60** [comment]
Hi @openworld-lab,

In this case setting `--fp16 True` might be sufficient to make the code work. However I did not test the code on V100 so can't say anything for sure. Thank You
