### ISSUE TITLE
Error when running the demo.

### ISSUE THREAD

**Issue by oximi123** [mbzuai-oryx/Video-ChatGPT#64]
Hi, I encouter the following error when running the demo in the website:

2023-11-01 14:03:15 | INFO | gradio_web_server | add_text. ip:. len: 51
2023-11-01 14:03:17 | ERROR | stderr | Traceback (most recent call last):
2023-11-01 14:03:17 | ERROR | stderr |   File "/home/user/anaconda3/envs/video_chatgpt/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
2023-11-01 14:03:17 | ERROR | stderr |     output = await app.get_blocks().process_api(
2023-11-01 14:03:17 | ERROR | stderr |   File "/home/user/anaconda3/envs/video_chatgpt/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
2023-11-01 14:03:17 | ERROR | stderr |     result = await self.call_function(
2023-11-01 14:03:17 | ERROR | stderr |   File "/home/user/anaconda3/envs/video_chatgpt/lib/python3.10/site-packages/gradio/blocks.py", line 898, in call_function
2023-11-01 14:03:17 | ERROR | stderr |     prediction = await anyio.to_thread.run_sync(
2023-11-01 14:03:17 | ERROR | stderr |   File "/home/user/anaconda3/envs/video_chatgpt/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
2023-11-01 14:03:17 | ERROR | stderr |     return await get_asynclib().run_sync_in_worker_thread(
2023-11-01 14:03:17 | ERROR | stderr |   File "/home/user/anaconda3/envs/video_chatgpt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
2023-11-01 14:03:17 | ERROR | stderr |     return await future
2023-11-01 14:03:17 | ERROR | stderr |   File "/home/user/anaconda3/envs/video_chatgpt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
2023-11-01 14:03:17 | ERROR | stderr |     result = context.run(func, *args)
2023-11-01 14:03:17 | ERROR | stderr |   File "/home/user/anaconda3/envs/video_chatgpt/lib/python3.10/site-packages/gradio/utils.py", line 549, in async_iteration
2023-11-01 14:03:17 | ERROR | stderr |     return next(iterator)
2023-11-01 14:03:17 | ERROR | stderr |   File "/home/user/botao/video-chatgpt/video_chatgpt/demo/chat.py", line 105, in answer
2023-11-01 14:03:17 | ERROR | stderr |     image_tensor = img_list[0]
2023-11-01 14:03:17 | ERROR | stderr | TypeError: 'NoneType' object is not subscriptable

**Comment by ntlm1686** [comment]
Hello @oximi123 , how did you solve this problem?
